### ISSUE TITLE
Alien vs Predator

### ISSUE THREAD

**Issue by Radagais** [SineSwiper/RimWorld-FactionBlender#1]
Is it compatible with Alien vs Predator? I know that it should supports most mods, but Xenomorphs from AVP have slightly different AI. 

https://steamcommunity.com/sharedfiles/filedetails/?id=1568400124&searchtext=alien

**Comment by SineSwiper** [comment]
Probably.  Try it and see.  If there's anything weird about it, let me know.

**Comment by SineSwiper** [comment]
FYI, I have this installed now and blacklisted the Xenomorphs in the latest release.  The Predator race still works fine, though.
