### ISSUE TITLE
TPS drops, wasted items bought from caravan

### ISSUE THREAD

**Issue by Melodeiro** [SineSwiper/RimWorld-FactionBlender#3]
On trade caravan arrival i have a huge tps drop, speed x3 works as slow as x1. Seems like caravan should have elephants, but they weren't spawned properly, and log is spammed with errors every tick. Also when i bought some items, they just disappeared (obviously was intended to be dropped from elephants). Before that spam started, i see that message:
`[FactionBlender] Unrecognized biome RRP_Savanna.  Accepting all pack animals for traders here, which might cause some to freeze/burn to death, if the biome is hostile.  Ask the dev to include the biome in the static min/max temp list.`
So maybe thats the reason. Would be nice to have a better behaviour when there is no settings for biome, instead of that, if this was caused by your mod, ofc.

Log: https://gist.github.com/f6eb3fd996c022a8732dbc38354571c4

**Comment by SineSwiper** [comment]
The unrecognized biome shouldn't cause the log spam.  It looks like all of the spam is from the RegionCostCalculator, which FB isn't messing with.  Not sure what mod is interfering, but I do see these lines in the stack traces:

```
Verse.AI.PathFinder.FindPath_Patch0
Verse.Pawn.Tick_Patch1
```

So, some other mod has some patches going on that may cause errors.

I can at least fix the biome issue.  Which mod adds the `RRP_Savanna` biome?  Is that Rainbeau's Realistic Planets?

**Comment by Melodeiro** [comment]
> Which mod adds the `RRP_Savanna` biome? Is that Rainbeau's Realistic Planets?

Since i have it installed, yes, probably

**Comment by SineSwiper** [comment]
Unfortunately, the two patch names above are too generic to really pinpoint the mod causing the problem.  A few of these mods might not expect animals to do certain things, like be in a raid or act as a guard animal for a trade caravan, and assume they can always access humanlike properties of a pawn.

As far as the Faction Blender biome warning, I did fix that in commit df6b0127337.  I'll get that in the next release.
