### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by strinkaj** [SineSwiper/RimWorld-FactionBlender#7]
Hey, love the idea of this mod, but I havent been able to use it yet! 

https://gist.github.com/8c7bea39e4b6101392e7e94245efec5c

I get this error on startup, any idea what is causing it? I am guessing a mod incompatibility but dont really know how to troubleshoot to find which mod. 

Keep up the great work!

**Comment by strinkaj** [comment]
Upon seeing the rest of the repo, seems like it is humanoid alien races, and there is a PR to fix in this repo

https://github.com/SineSwiper/RimWorld-FactionBlender/pull/6

**Comment by SineSwiper** [comment]
Fixed in #6
